# Generated by Django 3.2.9 on 2023-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='verifyuser',
            name='profile',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
