# Generated by Django 3.2.9 on 2023-01-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20230129_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyuser',
            name='profile',
            field=models.ImageField(default='https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg', upload_to='images/'),
        ),
    ]
