# Generated by Django 3.2.9 on 2023-01-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_verifyuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyuser',
            name='profile',
            field=models.ImageField(default='media/images/Group_1.png', upload_to='images/'),
        ),
    ]
