# Generated by Django 3.2.9 on 2023-01-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230128_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DTModel',
        ),
        migrations.AddField(
            model_name='booking',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
