# Generated by Django 3.2.9 on 2023-01-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230129_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='datetime',
        ),
        migrations.AddField(
            model_name='booking',
            name='pickupTime',
            field=models.TimeField(null=True),
        ),
    ]
