# Generated by Django 3.2.9 on 2023-01-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230129_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cost_per_day',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_days',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
