# Generated by Django 3.2.9 on 2023-01-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driverStatus',
            field=models.BooleanField(default=False),
        ),
    ]
