# Generated by Django 3.2.9 on 2023-02-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_paymentcomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.CharField(max_length=200),
        ),
    ]
