# Generated by Django 3.2.9 on 2023-02-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maxPower',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='maxTorque',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
