# Generated by Django 3.2.9 on 2023-02-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20230223_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcomplete',
            name='total_days',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
