# Generated by Django 3.2.9 on 2023-03-14 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_ratings_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcomplete',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ratings'),
        ),
    ]
